name: FINAL_RUNNER_TEST

on:
  push:
    branches: [master, develop]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Git Pull and Deploy
        run: |
          cd /ssd/docker/upload_articles/upload_article
          # Игнорираме проверката на Known Hosts, за да не гърми Runner-а
          export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"
          git pull origin master
          
          # Пускаме Docker (build-ваме наново само ако има промени)
          docker compose up -d --build
          
          echo "🚀 Митак, проектът е обновен успешно!"
