name: FINAL_RUNNER_TEST

on:
  push:
    branches: [master, develop]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Simple Hello
        run: |
          cd /ssd/docker/upload_articles/upload_article
          git pull origin master
          docker compose up -d --build
          echo "Браво, Митак! Рънерът работи без SSH!"
