name: FINAL_RUNNER_TEST

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Git Pull and Deploy
        run: |
          cd /ssd/docker/upload_articles/upload_article
          # Вече не ни трябва GIT_SSH_COMMAND, защото сме на HTTPS
          git pull origin master
          
          # Пускаме Docker
          docker compose up -d --build
          
          echo "🚀 Всичко е готово, Митак!"
